services:
  kvrocks:
    restart: always
    image: apache/kvrocks:latest
    entrypoint:
      - kvrocks
      - -c
      - /var/lib/kvrocks/kvrocks.conf
      - --resp3-enabled
      - "yes"
      - --bind
      - "0.0.0.0"
      - --pidfile
      - /var/run/kvrocks/kvrocks.pid
      - --dir
      - /data
      - --timeout
      - "360"
      - --rocksdb.compression
      - zstd
      - --workers
      - "2"
      - --rocksdb.write_buffer_size
      - "16"
      - --rocksdb.max_write_buffer_number
      - "1"
      - --rocksdb.max_open_files
      - "1024"
      - --rocksdb.enable_blob_files
      - "yes"
      - --rocksdb.read_options.async_io
      - "yes"
      - --requirepass
      - ${PASSWORD}
      - --port
      - ${PORT}
      - --lua-strict-key-accessing
      - "yes"
    volumes:
      - ./data/kvrocks:/data
      - ./conf/kvrocks:/var/lib/kvrocks
    ports:
      - ${PORT}:${PORT}
